### ISSUE TITLE
TriftPy ?

### ISSUE THREAD

**Issue by silpol** [vitalyrepin/orders-api#2]
Have you tried to use TriftPy [1](https://github.com/eleme/thriftpy) [2](https://thriftpy.readthedocs.org/en/latest/) ?

**Comment by vitalyrepin** [comment]
Hej,

No. Thanks for a link! Looks interestinng!

2015-05-08 22:25 GMT+03:00 A.T. notifications@github.com:

> Have you tried to use TriftPy 1 https://github.com/eleme/thriftpy 2
> https://thriftpy.readthedocs.org/en/latest/ ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vitalyrepin/orders-api/issues/2.

## 

WBR & WBW, Vitaly
